version: '2'
services:
  #The data Container will only act as a DATA Container that will expose DATA to others
  data:
    container_name: data
    build: ./data    
    privileged: true
    ports:
      - "139:139"
      - "445:445"
  #Simple console Container to test stuff
  console:
    container_name: "console-alpine"
    build: ./console